### ISSUE TITLE
ANSI gem

### ISSUE THREAD

**Issue by trans** [turn-project/turn#1]
Hi Tim. I've recently spun off facets/ansicode.rb as a stand-alone project --with some cool additional ANSI-related classes  (gem install ansi). So I just pushed the changes needed to swap out Turn's color support for the 'ansi' project. Please give it a whirl and if everything checks out, go ahead and release it at your discretion.

**Comment by TwP** [comment]
Sorry for the delay ... new version has been released and pushed out to gemcutter.
