### ISSUE TITLE
Display normalized method name

### ISSUE THREAD

**Issue by fnando** [turn-project/turn#10]
I added an option for displaying normalized method names. So instead of `test_some_method_name` the formatter will display `some method name      PASS`.

Here's the commit: c3fab87052642c234a0e1aed94e37a1084cecf0e

**Comment by defunkt** [comment]
-1

Showing `test_some_method_name` means you can run:

```
ruby test/test_file.rb -n test_some_method_name 
```

to execute only that single test. It also means you can run:

```
turn -n test_some_method_name
```

 to run tests matching that pattern.

**Comment by fnando** [comment]
That's why is disabled by default. :) 

In fact, I'd rather running my tests every time and prevent the noise added by the "test_" prefix and underscores.

**Comment by defunkt** [comment]
Oh, well then - cool!

Should it be a command line flag, too?

**Comment by fnando** [comment]
Haven't thought about the command line. Implemented as --normalize option.

Commit: b05da70c8b3b46820fcc12d4e2993db7cabbb330

**Comment by trans** [comment]
The commits seems to have been lost. If you still have this code please resubmit.

**Comment by trans** [comment]
The config option `Turn.config.natural=true` for putting in a test helper has been available for the last few versions or so. And I just added a command line option for it too, `--natural`. So we should (finally) be all good here.
