### ISSUE TITLE
Request: Do not display backtrace on SKIP

### ISSUE THREAD

**Issue by leehambley** [turn-project/turn#109]
It must be possible (but I couldn't find out how) to not display a backtrace when a test is skipped.

I see that `Skip` appears to be implemented as a error that is raised, and thus it would appear to trigger the same sort of code paths, I tried to examine how to improve that code, but I didn't have a lot of time to invest.

I'm throwing this issue request out there in the hope that someone with a better knowledge of the code can jump to a possible solution more quickly than I might.

**Comment by trans** [comment]
You are probably right that we don't need to show a backtrace for skipped tests. I'll have a look. But as this isn't as pressing as some of the other issues, I'm going to hold off on this until the release after next. In them meantime, if anyone else would like to tackle it, feel free.

**Comment by leehambley** [comment]
Could you point me in the right direction, just a hint (I did try and find it myself) and I'd be more than happy to find the code and make a patch with tests.

**Comment by trans** [comment]
Sure. This is the default reporter: https://github.com/TwP/turn/blob/master/lib/turn/reporters/pretty_reporter.rb. Notice that `skip()` calls `prettify()`. I think you are suggesting that `skip()` act like `pass()` instead.

Of course, we must consider first, do we really want to differentiate skip from the others (i.e. fail and error)? Are we sure we want to do this? Skip is usually meant to denote a "todo", so it helps to know where it is. So, if we do this, I would suggest two things: Allow a `--verbose` option to let it fallback to what it does now, and provide file and line number with the output message. Make sense?

**Comment by leehambley** [comment]
Thank you for the guidance @trans, I've implemented the simplest thing to keep my team sane in my fork, nothing beautiful, but the patch is at https://github.com/leehambley/turn/commit/9aef9d86242e58f8900f5d2140eab93826b429e6. I look forward to having some more time to address this issue a bit more fully, I'll close for the time being, and try and come back and make a more widely acceptable patch, including the option to re-enable the backtrace.
