### ISSUE TITLE
--name=PATTERN for test name filtering doesn't work

### ISSUE THREAD

**Issue by danielb2** [turn-project/turn#111]
See #6

Using 4.3.0

Tried to filter tests using -n and when turn is not required, this works fine. With turn, it matches no tests at all.

**Comment by trans** [comment]
Could you clarify? I just tried it on a test sample and it seems to be working.

**Comment by danielb2** [comment]
I'll have to see if I can get a test-case to repro again

**Comment by daniely** [comment]
This is a dupe #78 which is now fixed.
