### ISSUE TITLE
Need New Maintainer

### ISSUE THREAD

**Issue by trans** [turn-project/turn#113]
Turn needs a new maintainer. I have moved on to using Tapout (http://rubyworks.github.com/tapout) for my test reporting needs. So I don't have the time to spare to Turn any more.

So if anyone else would like to take over maintenance, say the word.

**Comment by citizen428** [comment]
I could be interested, what exactly would that involve and how would we go about it?

**Comment by daniely** [comment]
@citizen428 let's work on this together! I've been looking for something to contribute to and working with you again would be awesome! :smile:

**Comment by citizen428** [comment]
Excellent idea @daniely, I'd be up for that. :-)

**Comment by trans** [comment]
Super! All you really need to do is fork the repo and go for it. Once you guys get situated I'll contact Tim Pease (the author of the original version) so we can make your repo the new master and turn over release permissions on Rubygems.org. 

I'll be available to answer any questions you have about the current code.

**Comment by citizen428** [comment]
Sounds good! @daniely It's still gonna be a bit (although by now the "bit" is measured in weeks, not month ;-)) before I can dedicate more time to this, do you want to go ahead and fork it?

**Comment by daniely** [comment]
Let's do it! I'll fork the project.

**Comment by daniely** [comment]
Forked it to https://github.com/turn-project/turn where @citizen428 and I are the contributors.

Please make it the new master and release permissions on Rubygems.org.

As for questions, @trans what are some areas of turn that need some love?

**Comment by trans** [comment]
I just did a little house maintenance --clean up the licensing files, build files and added a CONTRIBUTING.md file to help you get started. Go ahead an pull those changes.

I'd recommend taking a little time to familiarize yourself with the code if you haven't already. Probably the hardest thing to understand is how the solo and cross runners work. Also, FYI testing can be a little tricky b/c Turn uses the very test framework it augments.

The primary issue that needs attention is #127 --MiniTest 5 compatibility.

Another decision that has to be made is whether to support the original [Test Unit](http://test-unit.rubyforge.org/) framework or to just let that go entirely. Tim and I made a decision a couple years back to focus on MiniTest. But the code for Test Unit is still in there. Although at this point I have no idea if it still works with the latest releases of Test Unit.

I'll leave the current issue board up for a while so you guys can weed through it. The most common issue I hear is the Turn isn't inter-operable with some other tool. Usually that has less to do Turn and more to do with MiniTest's design which requires monkey patching to augment, but as of MiniTest v5.0, which has a much improved API, that kind of issue should occur much less.

**Comment by citizen428** [comment]
Thanks @trans! For now MiniTest 5.0 compatibility is the most important thing, after that we can decide on whether or not we keep/update the support for Test Unit.

**Comment by trans** [comment]
Hey, @citizen428 and @daniely, I realized last night that we should handle the transfer differently since you created a new `turn-project` organization. Instead of the fork, I can have Tim transfer the current project to the new organization directly via the settings panel. That way all the stars, watches, wiki, etc. will be transfered too.

So to proceed I need you to delete your current fork. If you've made any commits so far just keep a local copy so you can reapply them. Once the fork's deleted I'll tell Tim to go ahead with the transfer. Shouldn't take long.

Also, Tim wants to continue to be involved in the project since it was his baby originally. Based on my experience, he's hands off and just wants to be kept in the loop about any major decisions.

**Comment by TwP** [comment]
Transferring the repository to another organization is easy peasy. As part of the transfer we'll also setup an alias from the no longer existent `twp/turn` repo to the new `turn-project/turn` repo.

Forked repositories don't show up by default in searches. You have to add the `fork:true` flag to get forks in the search results. Avoiding forks is good for SEO :sparkles: :tada:

**Comment by daniely** [comment]
@TwP we welcome you with :hand: open arms :hand:. I'll add you to the `turn-project`.

`turn-project` is now empty and ready for action

**Comment by citizen428** [comment]
@trans & @TwP Thanks a lot, transferring over the repo makes our lives a lot easier (issues etc)!

**Comment by TwP** [comment]
Transfer failed :disappointed: Apparently I need to be an admin on the `turn-project` org in order to transfer the repository.

![screen shot 2013-10-30 at 8 54 15 am](https://f.cloud.github.com/assets/6323/1437779/2f30e01c-4173-11e3-92b4-dc29baf58034.PNG)

**Comment by daniely** [comment]
@TwP made you an admin :smiley:

**Comment by trans** [comment]
Maybe I miss understand something about how github works. Why are there no members listed at https://github.com/turn-project?tab=members ?

**Comment by daniely** [comment]
@trans I believe it's because none of us have publicized our membership.

**Comment by daniely** [comment]
Do you see me now?

**Comment by trans** [comment]
Yep. :+1:

**Comment by jarrett** [comment]
Hello, and thanks for offering to maintain this project! I use it every day, so I was just wondering if it's still alive. In particular, do you anticipate adding [support for MiniTest 5](https://github.com/turn-project/turn/issues/127)? Thanks again! Let me know if there's anything I can do to help.

**Comment by citizen428** [comment]
Hi,

thanks for the much needed kick in the behind!

In fact we did take over maintainership of this project, but then I took a
job in another country (even another continent) and since then was pretty
wrapped up in preparations, the actual move and getting used to my new job.

If you feel like you can contribute to this project and are willing to do
so I'll add you to the team!

On Tue, Mar 4, 2014 at 12:33 AM, jarrett notifications@github.com wrote:

> Hello, and thanks for offering to maintain this project! I use it every
> day, so I was just wondering if it's still alive. In particular, do you
> anticipate adding support for MiniTest 5https://github.com/turn-project/turn/issues/127?
> Thanks again! Let me know if there's anything I can do to help.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/turn-project/turn/issues/113#issuecomment-36535189
> .

## 

Michael Kohl

http://citizen428.net | http://twitter.com/citizen428

**Comment by jarrett** [comment]
Thanks! I probably can help. I can't necessarily offer to be the primary
maintainer, since I already have a few projects of my own to maintain. But
I could pitch in. Have you had a chance to familiarize yourself with the
Turn codebase? (I myself have not, as of yet.)

**Comment by daniely** [comment]
"familiarize" is so subjective :)

But yes, I've been looking at the code but need to dig into it some more. @citizen428 and I both need to get our butts in gear here.

**Comment by jarrett** [comment]
Sounds good. Let me know when you're ready to dive in.

**Comment by daniely** [comment]
@jarrett if you want a place to start you can look at #78. This is causing our CI to fail.

**Comment by daniely** [comment]
@jarrett nvm, it's fixed :smile:

**Comment by trans** [comment]
@daniely and @jarrett, just thought I'd let you know I sat down and hacked out preliminary minitest v5 support today. Shouldn't take too much longer to finish.

Sorry your maintainership didn't work out. This will be my last work on this project, for certain. Afterward it's back to looking for new maintainers.

**Comment by daniely** [comment]
Sorry from my end as well.

It's awesome you're adding the much requested minitest v5 support.

**Comment by jarrett** [comment]
Thanks! I'm still interested in helping on this project. Though as before, I wouldn't be able to be the primary maintainer.
