### ISSUE TITLE
`Repository.name.gsub(/$/, 't')`

### ISSUE THREAD

**Issue by rick** [turn-project/turn#119]
![](https://github.campfirenow.com/room/539445/uploads/4124593/Photo+Booth-11.png)

**Comment by tnm** [comment]
cc @leehuffman

**Comment by trans** [comment]
I take it this is a joke?

Do you think you can do better? Please take over the project and have at it.

**Comment by rick** [comment]
![](http://i.imgur.com/1jqAT.png)

**Comment by trans** [comment]
Not upset. I am very serious! Been looking for a new maintainer for a while.

**Comment by rick** [comment]
I'm probably not the guy :-)  I actually just learned about this project (and presumed TwP was still maintaining it -- hence the joke).  I'll look more at it, but would be surprised if I can get up to maintaining it any time soon!
