### ISSUE TITLE
Disable "gem install minitest" warning.

### ISSUE THREAD

**Issue by 907th** [turn-project/turn#120]
I'm using turn with Unit::Test and always see "gem install minitest" warning on every kind of tests.

Message caused by ...

```
# lib/turn/minitest.rb:1-6
# make sure latest verison is used, rather than ruby's built-in
begin
  gem 'minitest'
rescue Exception
  warn "gem install minitest"
end
```

Can you suppress it?

**Comment by trans** [comment]
That can be done. But this surprises me somewhat. Some time ago we refocused Turn to support MiniTest _only_, and while the Test::Unit code (I assume that's what you mean by "Unit::Test") is still there and hasn't changed (and apparently still works okay) there were no real plans to continue that support into the future. OTOH, the whole Turn project is sort of like that right now, as it awaits a new maintainer if it is going to carry on.

If you really do mean Test::Unit as in http://test-unit.rubyforge.org/, then you might want to give [Tapout](http://rubyworks.github.com/tapout) a try (You will need that Test::Unit [adaptor](https://github.com/test-unit/test-unit-runner-tap)). I actively maintain Tapout now, whereas I only passively maintain Turn any longer.

**Comment by 907th** [comment]
Thanks! I'll try Tapout.
