### ISSUE TITLE
minitest-ci not generating xml files

### ISSUE THREAD

**Issue by redrick** [turn-project/turn#126]
Hi guys,

I really like this gem, but auch i got a problem and its a deal breaking one this time :(
so to sum it up I am usig jenkins and stuff to run tests for me and thus I need minitest-ci (BTW ruby2.0.0, rails4.0.0 app using minitest) and the `minitest-ci` do generate nice xml files with output of my tests like which failed and so on, we all know this stuff, but when I want to nicer look of tests and include `gem 'turn'` in my gemfile and then use `:outline` layout, it breaks, it does not generate those xmls for me and the whole deployment breaks :(

to show you what happens to me, I created an [example app](https://github.com/redrick/minitest_turn_demo), its nothing, just some scaffolded stuff, but you can see the file generation in test/reports directory...
and also to speed things up I created two branches, one with other without turn :)

thx for your time guys :+1:

**Comment by trans** [comment]
Are you using Minitest v5 or higher? If so Turn hasn't yet been updated to work with the latest version of Minitest.

Also, sometimes you have to use the `:require => false` option in the Gemfile w/ Turn.

**Comment by redrick** [comment]
it does not work either way...

I am on minitest 4.7.5 (minitest-rails gem) , I got problems running minitest 5.X with rails see this probably:

```
https://github.com/blowmage/minitest-rails/issues/112
```

but I kinda already gave up on running it in this setup, I just use turn on localhost and the comment it in production... I cannot find a better way :(

UPDATE:
I might as well close this one... not going to use it in production any time soon anyway :(
