### ISSUE TITLE
Retire rubyforge project?

### ISSUE THREAD

**Issue by trans** [turn-project/turn#128]
The URL http://codeforpeople.rubyforge.org/turn/ looks to be well out of date. It could of course be updated but probably at this point the whole Rubyforge project can just be retired. I imagine this would fall to Tim to ultimately decide and handle.

**Comment by citizen428** [comment]
Yes, as far as I can see there's no need for the Rubyforge project. How is the situation re RubyGems? From what I can tell you and Time are still the owners, can you add Daniel and me? /cc @TwP

**Comment by trans** [comment]
No problem. Just need your email addresses. Are the email address attached to your github accounts the ones to use for rubygems?

**Comment by citizen428** [comment]
In my case yes.

**Comment by trans** [comment]
Ok. You are added!

**Comment by TwP** [comment]
:+1: on killing the rubyforge project. It has not been touched in a very long time. "codeforpeople" is Ara Howard's old rubyforge project dumping ground ... that brings back memories!

**Comment by trans** [comment]
@TwP Indeed it does. It's weird. It feels almost like a different era. 

To get the rubyforge project removed I believe the only way is to request it via: http://rubyforge.org/forum/forum.php?forum_id=2

**Comment by tadman** [comment]
Ruby Forge is [shutting down May 15th, 2014](https://twitter.com/evanphx/status/399552820380053505), so this is basically a solved problem.

**Comment by daniely** [comment]
2482f0edd17c86f920fd8b18277eff5cf8d40e62 "fixes" this too.
