### ISSUE TITLE
MiniTest Support

### ISSUE THREAD

**Issue by trans** [turn-project/turn#13]
I recently pushed a "first small step toward MiniTest support". First let me apologize for pushing that directly to master. That was an accident. I thought I was pushing to my own fork. But maybe it's for the best b/c at some point this issue has to be addressed, and now is a good a time as any. 

I've been giving the issue some serious thought, I've become concerned that supporting both Test::Unit and MiniTest with the same code base will prove increasingly difficult. Already Test::Unit 2 has a number of new counts (omitted, pending, etc.). So not only will the runners need an adapter, but each reporter will also have to account for these distinctions.

So I am thinking that Turn might do well to split into two projects, one for Test::Unit and one for MiniTest. I think this is the best solution b/c it allows each project to evolve as needs be along with the underlying test framework they each augment. Of course, the two can continue to cross-pollinate.

**Comment by paydro** [comment]
This sounds like a good idea. I've been trying to plug the reporter code in, but if you have to have more if/else it'll get convoluted. Do you plan on keeping the two projects inside turn so there's one codebase or will you create a new codebase specifically for MiniTest?

Let me know if I can help!

**Comment by trans** [comment]
Haven't heard from Tim Pease yet, so I am not 100% sure yet which direction we will be taking.

But, I am having a slight change of heart from my earlier analysis. Instead of supporting the latest versions of Test::Unit I'm thinking we cut off support at Test::Unit v1.2.3 --the last version shipped with Ruby 1.8+. Going forward we only support MiniTest. The idea here being that Turn's goal is to improve Ruby's built-in test suite, whatever it may be. Since MiniTest is designed to simplify Test::Unit v1.2.3 and and carry-on from there, then we have no substantial issues with supporting both.

The more I think about it, the more I think this is the correct approach. Let me know what you think. If it sounds good I will start on building a proper Runner interface for MiniTest. If you can translate your output format into a proper Reporter subclass, then we will be good to go.

**Comment by paydro** [comment]
Yeah, this is great. Turn will just work with whatever is bundled with Ruby. I'll start hacking away at a Reporter subclass for MiniTest and show you what I have in the next few days.

**Comment by trans** [comment]
Cool. I have nearly completed the runner. I'm going to clean up the code a bit more, then I'll go ahead and push it up to master. The only thing that's changed with regards to the reporters are that #error and #fail take the actual exception raised, rather then a message argument. We may need to extend Exception and Test::Unit's and MiniTest's assertion classes to build a more uniform message. We'll see.

**Comment by trans** [comment]
Ok. I pushed it up. We (finally!) have full MiniTest support. I've tested against MiniTest 1.6 and Ruby 1.8.7.

**Comment by trans** [comment]
Closing issue.
