### ISSUE TITLE
Update Rubygem Release and Version Bump

### ISSUE THREAD

**Issue by tadman** [turn-project/turn#132]
The current release on Rubygems is 0.9.6 from June 2012. Is anyone able to release an updated version of this gem? There's been a lot of things that have been fixed and improved that'd be nice to have access to rather than relying on deploying from the more bleeding-edge `master`, though at least that remains an option.

This is probably related to the ownership hand-over, Issue #113.

**Comment by daniely** [comment]
We will try to cut a 0.9.7 release soon. I have a feature branch that's being reviewed.

**Comment by tadman** [comment]
Great news!

**Comment by daniely** [comment]
0.9.7 released
https://github.com/turn-project/turn/pull/133
