### ISSUE TITLE
Unable to run 'rake test'

### ISSUE THREAD

**Issue by mck9** [turn-project/turn#138]
The "turn" tests drops an error:

<pre>
> rake test
/home/marek/.rvm/rubies/ruby-1.9.3-p545/bin/ruby -Ilib bin/turn -Ilib -v test/*.rb
Warning: you should require 'minitest/autorun' instead.
Warning: or add 'gem "minitest"' before 'require "minitest/autorun"'
From:
  /home/marek/.rvm/gems/ruby-1.9.3-p545@turn/gems/minitest-5.4.0/lib/minitest/test.rb:1:in `<top (required)>'
  /home/marek/.rvm/gems/ruby-1.9.3-p545@turn/gems/minitest-5.4.0/lib/minitest/spec.rb:1:in `<top (required)>'
  /home/marek/git/turn/lib/turn/minitest.rb:10:in `<top (required)>'
  /home/marek/git/turn/lib/turn.rb:19:in `<top (required)>'
  bin/turn:2:in `<main>'
/home/marek/.rvm/gems/ruby-1.9.3-p545@turn/gems/minitest-5.4.0/lib/minitest/unit.rb:22: warning: already initialized constant VERSION
MiniTest::Unit::TestCase is now Minitest::Test. From /home/marek/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/test/unit/testcase.rb:8:in `<module:Unit>'
/home/marek/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/test/unit.rb:328:in `autorun': uninitialized class variable @@installed_at_exit in Test::Unit::Runner (NameError)
    from /home/marek/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/test/unit.rb:640:in `<top (required)>'
    from /home/marek/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /home/marek/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /home/marek/git/turn/test/helper.rb:8:in `<top (required)>'
    from /home/marek/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /home/marek/.rvm/rubies/ruby-1.9.3-p545/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /home/marek/git/turn/lib/minitest/turn_plugin.rb:186:in `block in plugin_turn_init'
    from /home/marek/git/turn/lib/minitest/turn_plugin.rb:186:in `each'
    from /home/marek/git/turn/lib/minitest/turn_plugin.rb:186:in `plugin_turn_init'
    from /home/marek/.rvm/gems/ruby-1.9.3-p545@turn/gems/minitest-5.4.0/lib/minitest.rb:73:in `block in init_plugins'
    from /home/marek/.rvm/gems/ruby-1.9.3-p545@turn/gems/minitest-5.4.0/lib/minitest.rb:71:in `each'
    from /home/marek/.rvm/gems/ruby-1.9.3-p545@turn/gems/minitest-5.4.0/lib/minitest.rb:71:in `init_plugins'
    from /home/marek/.rvm/gems/ruby-1.9.3-p545@turn/gems/minitest-5.4.0/lib/minitest.rb:122:in `run'
    from /home/marek/.rvm/gems/ruby-1.9.3-p545@turn/gems/minitest-5.4.0/lib/minitest.rb:55:in `block in autorun'
rake aborted!
Command failed with status (1): [/home/marek/.rvm/rubies/ruby-1.9.3-p545/bi...]

Tasks: TOP => test
(See full trace by running task with --trace)
</pre>

installed gems:

<pre>
*** LOCAL GEMS ***

ansi (1.4.3)
bigdecimal (1.1.0)
bundler (1.6.2)
bundler-unload (1.0.2)
coderay (1.1.0)
executable-hooks (1.3.1)
gem-wrappers (1.2.4)
io-console (0.3)
json (1.5.5)
method_source (0.8.2)
minitest (5.4.0, 2.5.1)
pry (0.10.0)
rake (10.3.2, 0.9.2.2)
rdoc (3.9.5)
rubygems-bundler (1.4.3)
rvm (1.11.3.9)
slop (3.5.0)
</pre>

**Comment by trans** [comment]
Yea, the tests will need to be overhauled for v5 compatibility. And I figure at this point it is best to just drop v4 support altogether. People can just use the older version of turn if they need that. Reasonable?

**Comment by mck9** [comment]
I think I found a bug in turn and wanted to check if it is turns problem or minitests. Therefore it would be good to have a running test suite. I checked out the 0.9.7 tag. All OK now.
