### ISSUE TITLE
Two warnings - uninitialized variable and ANSI block notation

### ISSUE THREAD

**Issue by djberg96** [turn-project/turn#15]
Turn 0.7.0
Ruby 1.8.7
Linux

<pre>
/usr/local/lib/ruby/gems/1.8/gems/turn-0.7.0/lib/turn.rb:12: warning: instance variable @io not initialized
use ANSI block notation for future versions
</pre>

**Comment by trans** [comment]
Thanks. These should be taken care of in the next release.

**Comment by djberg96** [comment]
Any ideas when 0.8.0 will be out?

**Comment by djberg96** [comment]
Oops, didn't mean to close. How do you reopen a closed item on github?

**Comment by rubyworks** [comment]
I haven't heard from Tim so I am not sure.

I think that last major issue was just getting the tests to run without Turn actually be installed --that proved a bit tricky b/c turn actually reinvokes itself to handle the isolated test modes. But, I think I licked the problem.

Nonetheless I am still waiting to hear back from Tim whether he's encountered any remaining problems or not.

If you can spare the dev cycles, it would be great if you could clone the repo and give it a test whirl and let me know if you encounter any issues.

One last note, I updated ANSI recently and removed the warnings.
