### ISSUE TITLE
turn fails, can't load 'test/unit/ui/console/testrunner'

### ISSUE THREAD

**Issue by insane-dreamer** [turn-project/turn#19]
Turn fails with minitest, ruby 1.9.2. Trying to require 'test/unit/ui/console/testrunner', which doesn't exist with minitest (only with test/unit).

**Comment by trans** [comment]
Which version of Turn are you using?

**Comment by insane-dreamer** [comment]
0.7.0

**Comment by trans** [comment]
v0.7.0 does not have support for minitest or Ruby 1.9. The latest repo has been updated for it though. If you're up for it, we could really use some beta testers to clone the git repo and run the tests (run 'test/runner' script) and report any issues.

**Comment by insane-dreamer** [comment]
I cloned the repo and ran test/runner and all tests passed. 

There's no gemspec file in the repo though, so I can't install the repo version as a gem in order to try it out with my rails project. Would it be possible to add that?

**Comment by trans** [comment]
I'll see what I can do. Tim Pease is in control of the gem, and whatever reason he's been putting off releasing it.

**Comment by waratuman** [comment]
Any idea when this will be released?

**Comment by trans** [comment]
Tim just informed me last night that he finally got it out the door. Yea!

**Comment by waratuman** [comment]
Sweet!

**Comment by trans** [comment]
Closing issue.
