### ISSUE TITLE
error running turn  with ruby 1.9.2

### ISSUE THREAD

**Issue by insane-dreamer** [turn-project/turn#20]
I get the following error when trying to run turn on a rails test suite with factory girl, on ruby 1.9.2, OSX, using the new turn 0.8.0 gem:

$ turn --solo -Ilib test/
LOADED SUITE 
test/factories/activities.rb
/Users/francis/.rvm/rubies/ruby-1.9.2-preview3/lib/ruby/1.9.1/syck.rb:135:in `load': instance of IO needed (TypeError)
    from /Users/francis/.rvm/rubies/ruby-1.9.2-preview3/lib/ruby/1.9.1/syck.rb:135:in`load'
    from /Users/francis/.rvm/gems/ruby-1.9.2-preview3/gems/turn-0.8.0/lib/turn/runners/isorunner.rb:90:in `block in test_loop_runner'
    from /Users/francis/.rvm/gems/ruby-1.9.2-preview3/gems/turn-0.8.0/lib/turn/components/suite.rb:72:in`each'
    from /Users/francis/.rvm/gems/ruby-1.9.2-preview3/gems/turn-0.8.0/lib/turn/components/suite.rb:72:in `each'
    from /Users/francis/.rvm/gems/ruby-1.9.2-preview3/gems/turn-0.8.0/lib/turn/runners/isorunner.rb:56:in`each_with_index'
    from /Users/francis/.rvm/gems/ruby-1.9.2-preview3/gems/turn-0.8.0/lib/turn/runners/isorunner.rb:56:in `test_loop_runner'
    from /Users/francis/.rvm/gems/ruby-1.9.2-preview3/gems/turn-0.8.0/lib/turn/runners/isorunner.rb:43:in`start'
    from /Users/francis/.rvm/gems/ruby-1.9.2-preview3/gems/turn-0.8.0/lib/turn/controller.rb:139:in `start'
    from /Users/francis/.rvm/gems/ruby-1.9.2-preview3/gems/turn-0.8.0/lib/turn/command.rb:199:in`main'
    from /Users/francis/.rvm/gems/ruby-1.9.2-preview3/gems/turn-0.8.0/lib/turn/command.rb:37:in `main'
    from /Users/francis/.rvm/gems/ruby-1.9.2-preview3/gems/turn-0.8.0/bin/turn:3:in`<top (required)>'
    from /Users/francis/.rvm/gems/ruby-1.9.2-preview3/bin/turn:19:in `load'
    from /Users/francis/.rvm/gems/ruby-1.9.2-preview3/bin/turn:19:in`<main>'

**Comment by trans** [comment]
Hi-- 

Looks like something is going wrong with stdout redirection in the outline format. If you have a moment could you try again using a different report format, eg. <code>-D</code> or <code>--pretty</code> and let me know if you get the same error or not?

**Comment by trans** [comment]
Ok. I tracked it down. Turns out an error message was being passed to the reporter when the error itself should have been passed.

I'll push it up stream and ask Tim to release 0.8.1. I'll let you know when it's released.

**Comment by insane-dreamer** [comment]
Sorry, didn't get to testing it again with the different syntax; but glad you found the problem. Thanks!

**Comment by trans** [comment]
Should now be fixed --as of v0.8.1. Tim, you can close this issue.
