### ISSUE TITLE
[turn 0.8.1] Wrong assertion count

### ISSUE THREAD

**Issue by druido** [turn-project/turn#22]
When fed the following test file:

```
class FooTest < MiniTest::Unit::TestCase
  def test_t1
    assert true
  end
end

class BarTest < MiniTest::Unit::TestCase
  def test_t2
    assert true
    assert true
  end
end
```

turn outputs:

2 tests, 5 assertions, 0 failures, 0 errors

I guess turn should reset some local counter, but it does not. On running the above, turn counts 2 assertions in test_t2, then it counts 3 (2+1) instead of 1 in test_t1, adding up to 5.

**Comment by trans** [comment]
Thanks. I'll see if I can track the issue down. Are you running 1.9 or 1.8 or Ruby?

**Comment by trans** [comment]
Now that I think about it for half a second you're probably using 1.9 b/c you're using MiniTest.

**Comment by trans** [comment]
Fixed in upcoming version 0.8.2. This was a bit more involved then if first appeared b/c latest version of MiniTest (2.0+) has changed quite a bit. But, this provided an opportunity to update Turn's MiniTest runner to match.

Given this fix is more extensive, it would be great if you (and anyone else) could pull down the latest commit and give it a whirl.

**Comment by druido** [comment]
Actually, I am using turn both with Ruby 1.8 (+ gem install minitest) and Ruby 1.9. I'd be happy to test the fix, but could you tell me how can I run a local copy of the gem? I have cloned the latest commit into mydir/turn, but if I run ./mydir/turn/bin/turn -I/full/path/to/mydir/turn/lib, turn doesn't seem to be able to find command.rb.

**Comment by trans** [comment]
Hmm... try

```
cd ./mydir/turn/bin/turn
ruby -Ilib bin/turn
```

**Comment by druido** [comment]
Ok, it works with the default formatter (using ruby 1.9). But if I use --pretty or any other output mode, I get:

Exception `NameError' at turn/lib/turn/runners/minirunner.rb:51 - uninitialized constant Turn::MiniRunner::StringIO
turn/lib/turn/runners/minirunner.rb:51:in`initialize': uninitialized constant Turn::MiniRunner::StringIO (NameError)
    from turn/lib/turn/controller.rb:147:in `new'
    from turn/controller.rb:147:in`start'
    from turn/lib/turn/command.rb:216:in `main'
    from turn/lib/turn/command.rb:37:in`main'
    from ./bin/turn:3:in `<main>'

But maybe this depends on the fact that I am running the gem locally.

**Comment by trans** [comment]
Ah ok. I added `require 'stringio'` to the top of minirunner.rb. That should take care of it.

**Comment by druido** [comment]
Thank you, require 'stringio' fixes the bug. I have run some tests, and I confirm that the assertion count is correct. One thing that I have found is that, instead of 'turn -n tests/_', now I have to write just 'turn tests/_'. Is that intended behaviour? If so, is there a way to know which version of turn is running? Otherwise, a script running turn may stop executing tests correctly after updating the gem.

**Comment by druido** [comment]
Sorry, I am not familiar with Markdown and I've overlooked the preview. I meant to write

turn -n tests/*

and

turn tests/*,

respectively.

**Comment by trans** [comment]
Unfortunately we never put the version in the code itself. Should have done that, but it was overlooked. I've added it now, but it doesn't do you much good for an old version. You might compare the help output of old vs new version and use that as a distinction.
