### ISSUE TITLE
[patch] fix for ruby 1.9

### ISSUE THREAD

**Issue by tmm1** [turn-project/turn#23]
```
diff --git a/lib/turn/controller.rb b/lib/turn/controller.rb
index cf35289..eb6a2d6 100644
--- a/lib/turn/controller.rb
+++ b/lib/turn/controller.rb
@@ -114,7 +114,7 @@ module Turn

     def files
       @files ||= (
-        fs = tests.map do |t|
+        fs = Array(tests).map do |t|
           File.directory?(t) ? Dir[File.join(t, '**', '*')] : Dir[t]
         end
         fs = fs.flatten.reject{ |f| File.directory?(f) }
```

fixes

```
ruby-1.9.2-p136/gems/turn-0.8.1/lib/turn/controller.rb:117:in `files': undefined method `map' for "test/**/{test,}*{,test}":String (NoMethodError)
  from ruby-1.9.2-p136/gems/turn-0.8.1/lib/turn/controller.rb:132:in `start'
  from ruby-1.9.2-p136/gems/turn-0.8.1/lib/turn/command.rb:199:in `main'
  from ruby-1.9.2-p136/gems/turn-0.8.1/lib/turn/command.rb:37:in `main'
  from ruby-1.9.2-p136/gems/turn-0.8.1/bin/turn:3:in `<top (required)>'
  from ruby-1.9.2-p136/bin/turn:19:in `load'
  from ruby-1.9.2-p136/bin/turn:19:in `<main>'
```

**Comment by trans** [comment]
I'm surprise that one slipped passed testing. Thanks for catching it.

Instead of converting `tests` in the `files` method, I think I'll create a `tests=` setter method to do it, and adjust the default setting to suite, so that `tests` is always an array. Let me know if you see anything wrong with this approach.

**Comment by carlosbrando** [comment]
I have the same error here.

  /Users/carlosbrando/.rvm/gems/ruby-1.9.2-p136/gems/turn-0.8.1/lib/turn/controller.rb:117:in `files': undefined method`map' for "test/*_/{test,}_{,test}":String (NoMethodError)
    from /Users/carlosbrando/.rvm/gems/ruby-1.9.2-p136/gems/turn-0.8.1/lib/turn/controller.rb:132:in `start'
    from /Users/carlosbrando/.rvm/gems/ruby-1.9.2-p136/gems/turn-0.8.1/lib/turn/command.rb:199:in`main'
    from /Users/carlosbrando/.rvm/gems/ruby-1.9.2-p136/gems/turn-0.8.1/lib/turn/command.rb:37:in `main'
    from /Users/carlosbrando/.rvm/gems/ruby-1.9.2-p136/gems/turn-0.8.1/bin/turn:3:in`<top (required)>'
    from /Users/carlosbrando/.rvm/gems/ruby-1.9.2-p136/bin/turn:19:in `load'
    from /Users/carlosbrando/.rvm/gems/ruby-1.9.2-p136/bin/turn:19:in`<main>'

**Comment by tmm1** [comment]
This was fixed on master.

Any chance of a new gem release?
