### ISSUE TITLE
Output buffered with ruby 1.8.7 and autotest

### ISSUE THREAD

**Issue by pyrat** [turn-project/turn#25]
When running autotest and turn with ruby 1.8.7 the output is all buffered until the end of the test run. This is a little bit annoying. Has anyone experienced this before?

It works fine with ruby 1.9.2 but would like it to work in a similar manner on 1.8.7. 

Any suggestions?

Cheers,
Alastair

**Comment by trans** [comment]
Not sure. I am not very familiar with autotest. I've been using <a href="http://github.com/mynyml/watchr">Watchr</a> instead.

My guess is that a $stdout.flush call is needed somewhere.

How do you have autotest setup? If I can reproduce the issue I might be able to figure out a solution.

**Comment by pyrat** [comment]
I have now switched to watchr myself as its great that you can easily create your own custom scripts. So we can just close this for the time being. 

Cheers,
Alastair

**Comment by trans** [comment]
Works for me! :-)

I leave it open for now. If anyone else reads this and wants to provide a patch, feel free.
