### ISSUE TITLE
Weird results/output with Mocha & Shoulda

### ISSUE THREAD

**Issue by justincase** [turn-project/turn#28]
Gems

```
group :test do
  # http://stackoverflow.com/questions/3118866/mocha-mock-carries-to-another-test/4375296#4375296
  gem 'mocha', :require => false # required in test_helper.rb at the bottom
  gem 'shoulda'
end
```

Test case

```
class EventTest < ActiveSupport::TestCase
  test "a sample mock" do
    mocky = mock(:name => "Steve")
  end

  test "assert the truth" do
    assert true
  end
end
```

Expected output (before using turn):

```
F.
Finished in 0.187605 seconds.

  1) Failure:
test_a_sample_mock(EventTest) [test/unit/event_test.rb:20]:
not all expectations were satisfied
unsatisfied expectations:
- expected exactly once, not yet invoked: #<Mock:0x100ee12a8>.name(any_parameters)


2 tests, 2 assertions, 1 failures, 0 errors, 0 skips
```

After adding turn:

```
EventTest:
     PASS test_a_sample_mock (0.18s) 
     PASS test_assert_the_truth (0.01s) 

Finished in 0.193767 seconds.

2 tests, 1 assertions, 0 failures, 0 errors, 0 skips
```

Heh. Where did my failure go? Requiring `turn` _before_ `shoulda` brings it back but breaks the output:

```
EventTest:
     FAIL test_a_sample_mock (0.18s) 
          not all expectations were satisfied
unsatisfied expectations:
- expected exactly once, not yet invoked: #<Mock:0x103382aa8>.name(any_parameters)
          test/unit/event_test.rb:20:in `block in <class:EventTest>'

 test_assert_the_truth (0.01s) 

Finished in 0.191906 seconds.

2 tests, 2 assertions, 1 failures, 0 errors, 0 skips
```

`test_the_truth` for example has no `PASS` status. Only when I remove mocha (and the mock test) completely does it return. Just adding `gem 'mocha', :require => false` was enough to make it disappear, without requiring it anywhere else.

Any ideas?

**Comment by justincase** [comment]
So, mocha monkey patches TestCase overriding the return value https://github.com/TwP/turn/blob/master/lib/turn/autorun/minitest.rb#L135

Worked around it here: https://github.com/justincase/mocha-turn/compare/2b4e868...48f4708

**Comment by cameel** [comment]
I think the correct way to fix this is to remove the monkey patch on run() and just wrap it. Here is my patch: https://github.com/TwP/turn/pull/38

The long term solution would be to change MiniTest itself so that it returns symbols from run().

**Comment by justincase** [comment]
This is fixed with Kamil's patch: https://github.com/TwP/turn/commit/c4314e7dbfb42d81472bd16c83d8334233b5cbb3. Cheers!
