### ISSUE TITLE
turn summary shows after all rake tasks

### ISSUE THREAD

**Issue by jro** [turn-project/turn#29]
If I require turn in the Gemfile

```
group :development, :test do
  gem 'turn'
end
```

And then a random non-test related rake task 

```
vagrant@vagrantup:~/conduit$ rake -n tmp:clear
(in /data/web/conduit/current)
** Invoke tmp:clear (first_time)
** Invoke tmp:sessions:clear (first_time)
** Execute (dry run) tmp:sessions:clear
** Invoke tmp:cache:clear (first_time)
** Execute (dry run) tmp:cache:clear
** Invoke tmp:sockets:clear (first_time)
** Execute (dry run) tmp:sockets:clear
** Execute (dry run) tmp:clear

=========================================================================
  pass: 0,  fail: 0,  error: 0
  total: 0 tests with 0 assertions in 0.000239 seconds
=========================================================================
```

**Comment by TwP** [comment]
Turn will load the Test::Unit library. The Test::Unit library registers an at_exit handler that will run your unit tests.

Modify your Gemfile to install turn but not load it in your development group. Turn should be loaded in your test_helper.rb file in your test folder.

TwP

**Comment by jro** [comment]
in Gemfile, in the development group
     gem 'turn', :require => []

and just requiring it in test_helper.rb does seem to work.  

Just an update in case it helps for the docs.
