### ISSUE TITLE
turn contains code copied from minitest, but does not credit the author

### ISSUE THREAD

**Issue by tenderlove** [turn-project/turn#32]
[From minitest](https://github.com/seattlerb/minitest/blob/master/lib/minitest/unit.rb#L639-647)

[From turn](https://github.com/TwP/turn/blob/master/lib/turn/runners/minirunner.rb#L146-154)

**Comment by TwP** [comment]
ZOMG HELLO!!

I assume author attribution will suffice to close this issue? In your opinion, should attribution appear in the file itself or in the project README or the HISTORY??

**Comment by tenderlove** [comment]
zomg!

Probably should be along with the copyright, since that's what [Ryan's license says](https://github.com/seattlerb/minitest/blob/master/README.txt#L260-261).

:-)

**Comment by zenspider** [comment]
Wow... good job @trans... you putz. This is exactly why I've called you out as a plagiarist in the past... Won't be the last time either.

@TwP, yeah. _sigh_ it'd be nice if this didn't come up at all, but since it did copyright + attribution would be sufficient.

**Comment by zenspider** [comment]
@TwP, alternatively, you can nuke this file and I can provide you with a non-hackilicious version that works with minitest properly.

**Comment by TwP** [comment]
@zenspider Fantastic! Discussing such an option with tenderlove on irc right now. He has expressed the desire for turn to hook into minitest's IO subsystem. I agree with him completely.

**Comment by trans** [comment]
Yea, it really shows the difference in our character doesn't it. I did alot a work on Turn and I never asked for any credit. So accusing me of being a plagiarist is simply libel on your part. 

The method is a copy of the MiniTest method that provided a fix for a <i>subclass of a MiniTest class</i> and the old API of MiniTest required it to work. It wasn't used to misrepresent itself as anything else.

There's also the question of definition of "substantial portions". But that doesn't really matter, b/c this was brought up as merely an opportunity to attack me. How sad for you.

**Comment by tenderlove** [comment]
@trans actually I brought it up.  I was browsing the source and noticed much of it looked like Ryan's code.  I wondered why Ryan would copy his code around (rather than make turn depend on minitest or something), so I looked for attribution and there was none.

The two bits I linked to were just an example.  Minitest has changed since it was copied in here, and I am too lazy to track down diffs to show history.

**Comment by zenspider** [comment]
plagiarism - noun - the practice of taking someone else's work or ideas and passing them off as one's own.

libel - noun - a published false statement that is damaging to a person's reputation; a written defamation.

You're a plagiarist, plain and simple. You took my work and passed it off as your own, violating my license in the process. That's not libel, that's fact. Seems pretty straightforward to me. Even if it weren't fact, it couldn't be libel either as by now you have no reputation to speak of.

Weren't you leaving? We're still waiting...

**Comment by trans** [comment]
"Much of it"? 

The vast majority of this code was written before MiniTest existed. Turn did not even work with MiniTest until recently. Only two files apply to MiniTest which are the file you mention and the auntorun file. The autorun file was submitted by another contributor which I incorporated and later used as a bases to write the runner class. 

That these files reflect Ryan code at all is simply b/c it's whole purpose of them is to interface with Ryan's code (MiniTest), B/c at the time MiniTests API wasn't as mature it required copying a few lines of code to make it work --in other words it was a "depend"ency issue. I have no problem with Ryan being credited where he is do, but don't try to claim that "much of it" is Ryan's work.

**Comment by trans** [comment]
Notices posted.
