### ISSUE TITLE
Report the seed number when running in minitest mode

### ISSUE THREAD

**Issue by janxious** [turn-project/turn#41]
It is a valuable piece of information that you normally get with minitest that disappears when I include turn.

**Comment by trans** [comment]
Good point. We'll see what we can do.

**Comment by myoung8** [comment]
+1

**Comment by trans** [comment]
Any one want offer a patch?

**Comment by trans** [comment]
Done. Seed now appears in default outline reporter and pretty reporter output. Will add seed output to other reporters in future.

Thanks.

**Comment by janxious** [comment]
Nice. Thanks!
