### ISSUE TITLE
ASCI Colours don't display properly in cmd

### ISSUE THREAD

**Issue by michaelcm** [turn-project/turn#43]
We use cmd.exe for most of our coding as we do not like to require the use of cygwin or supplementary prompts.

The output is very hard to read:
←[33m    ERROR←[0m testPasswordChange (1.59s)

I am also filing a bug report with the ANSI gem, as the fail to detect win32 on my machine as the RUBY_PLATFORM=i386mingw32 and it looks for win32.

Can a flag of some sort be added to support the disabling of colours?

I tried removing ansi because the turn documentation is written such that it should use it if found, and otherwise not. This is the error I get without the ansi gem installed:
  C:/Ruby192/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb:247:in `to_specs': Could not find ansi (>= 1.2.2) amongst [builder-3.0.0, commonwatir-1.8.1, firewatir-1.8.1, hoe-2.9.4, minitest-1.6.0, nokogiri-1.4.4.1-x86-mingw32, rake-0.8.7, rd
oc-2.5.8, rubygems-update-1.8.5, s4t-utils-1.0.4, turn-0.8.1, user-choices-1.1.6.1, watir-1.8.1, win32-api-1.4.8-x86-mingw32, win32-process-0.6.5, win32console-1.3.0-x86-mingw32, windows-api-0.4.0, windows-pr-1.2.0, xml-simple-1.0.16] (Gem::LoadError)
        from C:/Ruby192/lib/ruby/site_ruby/1.9.1/rubygems/specification.rb:759:i
n`block in activate_dependencies'

Thanks!

**Comment by trans** [comment]
Next version of ANSI will have a global deactivation flag to turn off colors. I'll bump it to the top of my todo list and get it out asap.

**Comment by trans** [comment]
If you have `ANSICON` installed on your system, the upcoming release should work fine, color and all.

Otherwise, you will be able to turn off color in your test helper with the new config option `Turn.config.ansi=false`.

You should be able to turn off color support now by setting `$ansi=false`.
