### ISSUE TITLE
Result format inconsistent when running on ruby 1.8.7 vs 1.9.2

### ISSUE THREAD

**Issue by michaelcm** [turn-project/turn#44]
Both installs of ruby have turn 0.8.2 installed.

When running on 1.9.2 the PASS/FAIL is to the left of the test function, with the individual time to execute to the right of the function. Only the first line of the backtrace is available in this version.

When running on 1.8.7 the PASS/FAIL are right aligned, and there is no individual test execution time. The full backtrace is available in this version.

Ideally I would love to have:
- all the output from 1.9.2 on both versions, with a full backtrace.

Is it a default that has change that can be toggled by setting a config option or variable? I am not using the turn command line tool so it can't be a command line parameter.

**Comment by trans** [comment]
Thanks for reporting. I'll look into it when I get a moment and make sure it gets fixed for the next release. The next release will also allow for adjusting configuration while using auto-runners.

**Comment by michaelcm** [comment]
Thank you for looking into this. We actually ended up using/extending MiniTest to run the tests in the way we require as well as reporting the output we require. I'll keep Turn in mind for future projects, but once I grasped the full scope of what we are trying to active I see it is not a good match.

**Comment by trans** [comment]
This is fixed.

Sorry to hear Turn wasn't a good match for your needs. You may want to have a look at (tapout)[http://rubyworks.github.com/tapout].
