### ISSUE TITLE
Only show STDOUT/STDERR on fail?

### ISSUE THREAD

**Issue by defunkt** [turn-project/turn#5]
I love how Python's nose suppresses STDOUT and only shows it for tests that fail. I've hacked a basic version of that functionality into turn: 
http://github.com/defunkt/turn/commit/only_show_stdout_on_fail

**Comment by trans** [comment]
Hmm... Looks like it was done for both STDOUT and STDERR. I disabled it for STDERR in my latest work as it seemed redundant as I want greater control over the way the error gets displayed.
