### ISSUE TITLE
turn steps on mocha's teardown

### ISSUE THREAD

**Issue by leehambley** [turn-project/turn#53]
Here's a case to reproduce (sorry, no Gemfile, but the versions of gems/etc (current) are all present):
- https://gist.github.com/38421e26463d4aba575a

And here's the issue upstream with `mocha`:
- https://github.com/floehopper/mocha/issues/33

**tl;dr** Something when `turn` is required prevents `mocha`'s teardown running, so wide-reaching stubs, expectations and mocks aren't cleaned up. Not normally a problem when using instance-level stubs/expectations; but with `any_instance` for example, it makes problems.

Under disperate load order conditions (that is `:test_unit, :turn, :mocha` vs. `:test_unit, :mocha, :turn`) - the former passes all tests, but the word `PASS` is absent.

There's a lot more discussion and examples at the [mocha issue](https://github.com/floehopper/mocha/issues/33), the issue remains open in case that a cooperative fix requires some modification to `mocha`.

Apologies that the test-case isn't quite the simplest it could be, hopefully it's simple enough to follow.

**Comment by trans** [comment]
Hi, are you using the latest repo code, or the latest gem release?

**Comment by leehambley** [comment]
Gem release, how far ahead is master? (gem versions were in the gist)

On Wednesday, 21 September 2011, 7rans <
reply@reply.github.com>
wrote:

**Comment by trans** [comment]
Pretty far. I recently made the last big design change that has been in the works for some time, i.e. the auto-runners now uses the same code as the command line runners (where as they used to use separate code bases). I'd recommend giving the repo a try and see if it fixes the problem. The new code would benefit from some hands on tryouts in any case in prep for a new release.

**Comment by leehambley** [comment]
This does fix the mocha issue (nice one!)

It also introduces an issue, which I won't write an issue for, as it's unreleased code, but using `pending` in a test-case causes:

``` log
ShowRoutingTest
     test_should_route_pagionated_show_filters                           ERROR
        wrong number of arguments (0 for 1)
        STDERR:
        Exception `ArgumentError' at /Users/codebeaker/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/mocha-0.10.0/lib/mocha/integration/mini_test/version_230_to_251.rb:36:in `rescue in run'
        /Users/codebeaker/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/mocha-0.10.0/lib/mocha/integration/mini_test/version_230_to_251.rb:47:in `run'
        /Users/codebeaker/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/activesupport-3.1.0/lib/active_support/testing/setup_and_teardown.rb:35:in `block in run'
        /Users/codebeaker/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/activesupport-3.1.0/lib/active_support/callbacks.rb:453:in `_run_setup_callbacks'
        /Users/codebeaker/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/activesupport-3.1.0/lib/active_support/callbacks.rb:81:in `run_callbacks'
        /Users/codebeaker/.rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/activesupport-3.1.0/lib/active_support/testing/setup_and_teardown.rb:34:in `run'
```

As you can see, less than ideal - I'm not 100% sure where it's coming from; I couldn't trace it effectively.
