### ISSUE TITLE
Support for test-unit 2.x gem's "omit" and "pending"

### ISSUE THREAD

**Issue by suan** [turn-project/turn#54]
turn does not correctly handle these - would be nice if it did

**Comment by trans** [comment]
Turn doesn't _officially_ support test-unit 2.x b/c Ruby moved to minitest as the built-in test framework, but if you would like to submit some patches to handle that, that would be great. FYI, to this end, I'm not sure if the current test-unit test runner can be adjusted to handle both 1.x and 2.x, or if a new runner needs to be created.

**Comment by suan** [comment]
Honestly I don't know when I can get around to creating a patch, but it would be great if you could tag this as a feature request and leave it open?

**Comment by trans** [comment]
This will be resolved with the next major version series of Turn (which will probably be called 2.x series).
