### ISSUE TITLE
Incompatibility with recent MiniTest

### ISSUE THREAD

**Issue by phiggins** [turn-project/turn#58]
Hey guys,

[Recently a MiniTest user reported a failure using MiniTest::Spec with turn](https://github.com/seattlerb/minitest/issues/50). Here's a minimal testcase to demonstrate the problem:

```
gem 'minitest'
require 'minitest/autorun'
require 'turn'

describe String do
  before do
    @string = String.new
  end

  it 'is empty' do
    @string.must_be :empty?
  end
end
```

Running that results in this output:

```
pete@balloon /tmp $ ruby minitest_and_turn.rb 
Loaded suite minitest_and_turn
Started

String:
    ERROR test_0001_is_empty (0.00s) 
          NoMethodError: undefined method `empty?' for nil:NilClass
          (eval):6:in `must_be'


Finished in 0.001434 seconds.

1 tests, 0 assertions, 0 failures, 1 errors, 0 skips
```

The good news is that the unreleased git master version of turn works with the most recent MiniTest. Is there an ETA on a new release?

**Comment by BMorearty** [comment]
In the meantime (until such a release happens) if you want the latest `turn` from github, putting this in your `Gemfile` will do the trick:

```
gem 'turn', require: false, git: 'https://github.com/TwP/turn.git'
```

**Comment by BMorearty** [comment]
(or use 1.8 hash syntax if you are on 1.8.7)

**Comment by trans** [comment]
It took a few months, but a new release is finally right around the corner.
