### ISSUE TITLE
Add -n --name=PATTERN for test name filtering

### ISSUE THREAD

**Issue by rtomayko** [turn-project/turn#6]
[1b1655c](http://github.com/rtomayko/turn/commit/name_pattern) adds a `-n` option for selecting tests by name like `testrb`.

I also have a [tiny bullshit patch](http://github.com/rtomayko/turn/commit/9d31259e507dccbd57f4bbb8016295699827456d).

Great project. Thanks!

**Comment by TwP** [comment]
Both patches applied.
rtomayko has earned the commit bit.
Use your power wisely!

TwP
