### ISSUE TITLE
Incompatibility with minitest & mocha when using :skip

### ISSUE THREAD

**Issue by davekrupinski** [turn-project/turn#62]
When referencing the method :skip using the latest versions of minitest, turn, and mocha an ArgumentError is thrown (from inside mocha, but does not occur when turn is disabled).  Here are the gems used 

  gem 'rails', '3.0.10'
  gem 'mocha', '0.10.0'
  gem 'turn', '0.8.3'
  gem 'minitest', "2.6.2"

Here is the error that is produced:

``` ruby
        wrong number of arguments (0 for 1)
        STDERR:
        Exception `ArgumentError' at /Users/dave/.rvm/gems/ruby-1.9.2-p290@laika/gems/mocha-0.10.0/lib/mocha/integration/mini_test/version_230_to_251.rb:36:in `rescue in run'
        /Users/dave/.rvm/gems/ruby-1.9.2-p290@laika/gems/mocha-0.10.0/lib/mocha/integration/mini_test/version_230_to_251.rb:47:in `run'
        /Users/dave/.rvm/gems/ruby-1.9.2-p290@laika/gems/activesupport-3.0.10/lib/active_support/testing/setup_and_teardown.rb:35:in `block in run'
        /Users/dave/.rvm/gems/ruby-1.9.2-p290@laika/gems/activesupport-3.0.10/lib/active_support/callbacks.rb:444:in `_run_setup_callbacks'
        /Users/dave/.rvm/gems/ruby-1.9.2-p290@laika/gems/activesupport-3.0.10/lib/active_support/testing/setup_and_teardown.rb:34:in `run'
```

When turn is removed from the bundle, the behavior reverts to the normal "S" being output along with the the skip error message.

**Comment by jpcody** [comment]
+1, Thanks for bringing this up, Dave.

**Comment by cvshepherd** [comment]
Is this really a turn issue? I just tried using skip() in a standard Rails unit-test, and had the same error as above, only that the stack-trace ended at setup_and_teardown.rb:35. No mocha and no turn involved.

**Comment by cpence** [comment]
I can confirm this being a Turn bug.  Remove turn from the bundle, call minitest via the standard Rake autorunner, get 'S's in the output.  Add turn back in, call tests from command line, get the exception, tests fail with "ERROR".  I've gotten the same output both with the gem versions listed here, as well as the latest minitest.

**Comment by juniorz** [comment]
I tried to debug this all night, but that is damn hard, since the backtrace is not so useful.

**Comment by trans** [comment]
I applied the patch. Thank you @juniorz!
