### ISSUE TITLE
putting turn in Gemfile causes spurious test run summary

### ISSUE THREAD

**Issue by aspiers** [turn-project/turn#67]
If I put `gem 'turn'` in my `Gemfile` and then run a task e.g. `rake routes`, then I see this at the bottom of the list of routes:

```
LOADED SUITE test,test/functional,test/unit,test/unit/helpers,test/performance
MiniTest::Spec
==============================================================================
  pass: 0,  fail: 0,  error: 0
  total: 0 tests with 0 assertions in 0.001157612 seconds
==============================================================================
```

The workaround is instead to use

```
gem 'turn', :require => false
```

If this behaviour is intentional, it should be documented; otherwise it should be fixed.

**Comment by aspiers** [comment]
I think the fundamental problem here is that there are no instructions on how to use turn with Rails apps (forgive me if I've missed it!)

**Comment by trans** [comment]
That's an interesting side effect of Bundler, as Bundler has decided it's supposed to require everything listed in Gemfile instead of letting the running app load things as needed. I personally consider that a flaw with Bundler. Many programs I write have conditional requires, only loading certain parts of code if needed, and sometimes order of loading matters!!!

Be that as it may. The fact remains that `require 'turn'` autoruns unit test as a concise convenience for adding that line to test scripts.  That leaves us with two options:

1) Necessitate that users change `require 'turn'` to `require 'turn/autorun'`.

2) Prominently Document the fact the the Gemfile needs the :require => false option and be satisfied with that.

The first option has the adverse effect of requiring everyone who has been doing it this way (most people) to go back and change their code. That blows chunks, but maybe is ultimately what has to be done. (But not until after I beat on some Bundler devs for a bit ;-)

In the mean time I will put some info in the README on this issue, so at least it's is prominently elucidated, as you suggest.

Very much appreciate your reporting this. Let me know if you have any additional suggestions.

**Comment by aspiers** [comment]
Thanks.  As per issue #70, some documentation on how turn can be used with Spork would be extremely helpful.  Spork is unfortunately very important for many Rails developers due to Ruby/Rails' appallingly slow startup times.

**Comment by trans** [comment]
[Update] I have decided to transition to `require 'turn/autorun'`. Full change over will wait until v1.0 release (which shouldn't be too far off at this point). In the meantime, it will issue a warning to get people motivate to transition, and we will still have to use the `:require => false` trick, which I have documented in the README.

Let me know if there is anything else you think I need to do on this. Thanks.

**Comment by aspiers** [comment]
> Let me know if there is anything else you think I need to do on this.

Only the docs on Spork integration. Thanks :)

**Comment by aspiers** [comment]
To elaborate, I put

```
gem 'turn', :require => false
```

in my `Gemfile`, and

```
require 'turn/autorun'
```

in the `Spork.prefork` section of `test/test_helper.rb`, and I get:

```
$ guard
Guard uses Libnotify to send notifications.
Guard is now watching at '/data/music/RotC/eventbook'
Starting Spork for Test::Unit
Using TestUnit
Preloading Rails environment
Loading Spork.prefork block...
cannot load such file -- turn/autorun (LoadError)
/home/adam/.rvm/gems/ruby-1.9.3-p0@rails-3.1/gems/activesupport-3.1.3/lib/active_support/dependencies.rb:240:in `require'
/home/adam/.rvm/gems/ruby-1.9.3-p0@rails-3.1/gems/activesupport-3.1.3/lib/active_support/dependencies.rb:240:in `block in require'
/home/adam/.rvm/gems/ruby-1.9.3-p0@rails-3.1/gems/activesupport-3.1.3/lib/active_support/dependencies.rb:223:in `block in load_dependency'
```

This is probably because I am wildly guessing how to set it up in the absence of any docs on the matter :)

**Comment by trans** [comment]
Try just `require 'turn'` in Spork.prefork section for now. The `autorun.rb` file is a new addition and isn't available until next release (v0.9).

**Comment by aspiers** [comment]
Unfortunately that completely breaks it:

```
undefined method `setup_argv' for Test::Unit:Module
/home/adam/.rvm/gems/ruby-1.9.3-p0@rails-3.1/gems/spork-testunit-0.0.6/lib/spork/test_framework/test_unit.rb:29:in `run_tests'
/home/adam/.rvm/gems/ruby-1.9.3-p0@rails-3.1/gems/spork-0.9.0.rc9/lib/spork/run_strategy/forking.rb:13:in `block in run'
/home/adam/.rvm/gems/ruby-1.9.3-p0@rails-3.1/gems/spork-0.9.0.rc9/lib/spork/forker.rb:21:in `block in initialize'
/home/adam/.rvm/gems/ruby-1.9.3-p0@rails-3.1/gems/spork-0.9.0.rc9/lib/spork/forker.rb:18:in `fork'
/home/adam/.rvm/gems/ruby-1.9.3-p0@rails-3.1/gems/spork-0.9.0.rc9/lib/spork/forker.rb:18:in `initialize'
/home/adam/.rvm/gems/ruby-1.9.3-p0@rails-3.1/gems/spork-0.9.0.rc9/lib/spork/run_strategy/forking.rb:9:in `new'
/home/adam/.rvm/gems/ruby-1.9.3-p0@rails-3.1/gems/spork-0.9.0.rc9/lib/spork/run_strategy/forking.rb:9:in `run'
/home/adam/.rvm/gems/ruby-1.9.3-p0@rails-3.1/gems/spork-0.9.0.rc9/lib/spork/server.rb:48:in `run'
/home/adam/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/drb/drb.rb:1548:in `perform_without_block'
/home/adam/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/drb/drb.rb:1508:in `perform'
/home/adam/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/drb/drb.rb:1586:in `block (2 levels) in main_loop'
/home/adam/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/drb/drb.rb:1582:in `loop'
/home/adam/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/drb/drb.rb:1582:in `block in main_loop'
```

**Comment by trans** [comment]
Just looked at the code for Spork, looks like someone added explict support for Turn (https://github.com/sporkrb/spork-testunit/blob/master/lib/spork/test_framework/test_unit.rb#L42-L54)

So I think you might just need to

```
require 'turn/controller'
```

To get Turn loaded in w/o the autorunner. Let me know if that works for you.

(Note in the next release I'll have it working with just `require 'turn'`.)

**Comment by aspiers** [comment]
I get the same `setup_argv` error with `require 'turn/controller'` :-(

**Comment by trans** [comment]
Hmm... what version of Spork are you using. If it is the latest, is their a new release coming up. I ask b/c take a look at line 55: https://github.com/sporkrb/spork-testunit/blob/master/lib/spork/test_framework/test_unit.rb#L55

**Comment by aspiers** [comment]
Good point, that code comes from a pull request which got merged in November after the latest release (0.0.7).  However, `spork-testunit` [is](https://github.com/sporkrb/spork-testunit/issues/28) [fundamentally](https://github.com/sporkrb/spork-testunit/issues/33) [broken](https://github.com/sporkrb/spork-testunit/issues/42) so I am forced to move to RSpec ...

**Comment by trans** [comment]
Honestly RSpec is overrated (to put it nicely). Have any interest in being a "beta" tester for a new (very awesome) test framework?

In any case this issue should now be resolved. Use `require 'turn/autorun'` in `test_helper.rb` form now on.

**Comment by aspiers** [comment]
Thanks a lot. I might find time for beta-testing something new, but probably only if there are good docs and it is at least near feature parity with RSpec.

**Comment by chrisbloom7** [comment]
Using the latest versions of Turn, MiniTest, and Spork in a Rails 3.2 app with Ruby 1.9.2. I had to use both `gem 'turn', :require => false` in my Gemfile and `require "turn/autorun"` in test_helper, otherwise generators would fail with an `.../minitest/unit.rb:1010:in 'block in process_args': invalid option: --some-option (OptionParser::InvalidOption)` error whenever ANY option was passed in to the generator, and all my rake tasks would end with the test summary output that @aspiers mentioned in the OP.

**Comment by trans** [comment]
Is it open source? Could I have a look?  Or even better, if it's not too much trouble, could you create a project "skeleton" with just enough to demonstrate the problem?

**Comment by trans** [comment]
Also, have you tried it without Spork? I wonder if it has something to do with this:
  https://github.com/sporkrb/spork-testunit/blob/master/lib/spork/test_framework/test_unit.rb#L42-L56

**Comment by chrisbloom7** [comment]
https://github.com/chrisbloom7/turn_errors

clone then bundle install.

```
$ rake db:migrate
Loaded Suite test,test/performance

Started at 2013-01-16 08:51:13 -0500 w/ seed 3532.

Finished in 0.000116 seconds.

0 tests, 0 passed, 0 failures, 0 errors, 0 skips, 0 assertions


chrisbloom7@berner ~/Projects/Temp/turn_errors (master)
$ rails g scaffold SomeThing name:string --pretend
      invoke  active_record
      create    db/migrate/20130116135133_create_some_things.rb
      create    app/models/some_thing.rb
      invoke    mini_test
      create      test/models/some_thing_test.rb
      create      test/fixtures/some_things.yml
      invoke  resource_route
       route    resources :some_things
      invoke  scaffold_controller
      create    app/controllers/some_things_controller.rb
      invoke    erb
      create      app/views/some_things
      create      app/views/some_things/index.html.erb
      create      app/views/some_things/edit.html.erb
      create      app/views/some_things/show.html.erb
      create      app/views/some_things/new.html.erb
      create      app/views/some_things/_form.html.erb
      invoke    mini_test
      create      test/controllers/some_things_controller_test.rb
      invoke    helper
      create      app/helpers/some_things_helper.rb
      invoke      mini_test
      create        test/helpers/some_things_helper_test.rb
      invoke  assets
      invoke    coffee
      create      app/assets/javascripts/some_things.js.coffee
      invoke    scss
      create      app/assets/stylesheets/some_things.css.scss
      invoke  scss
      create    app/assets/stylesheets/scaffolds.css.scss
/Users/chrisbloom7/.rvm/gems/ruby-1.9.3-p327@turn_errors/gems/minitest-4.4.0/lib/minitest/unit.rb:1010:in `block in process_args': invalid option: --pretend (OptionParser::InvalidOption)
    from /Users/chrisbloom7/.rvm/gems/ruby-1.9.3-p327@turn_errors/gems/minitest-4.4.0/lib/minitest/unit.rb:989:in `new'
    from /Users/chrisbloom7/.rvm/gems/ruby-1.9.3-p327@turn_errors/gems/minitest-4.4.0/lib/minitest/unit.rb:989:in `process_args'
    from /Users/chrisbloom7/.rvm/gems/ruby-1.9.3-p327@turn_errors/gems/minitest-4.4.0/lib/minitest/unit.rb:1039:in `_run'
    from /Users/chrisbloom7/.rvm/gems/ruby-1.9.3-p327@turn_errors/gems/minitest-4.4.0/lib/minitest/unit.rb:1032:in `run'
    from /Users/chrisbloom7/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/test/unit.rb:21:in `run'
    from /Users/chrisbloom7/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/test/unit.rb:326:in `block (2 levels) in autorun'
    from /Users/chrisbloom7/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/test/unit.rb:27:in `run_once'
    from /Users/chrisbloom7/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/test/unit.rb:325:in `block in autorun'
```

Change the gemfile to read `gem 'turn', :require => false` instead and the issues go away
