### ISSUE TITLE
Only display failed test

### ISSUE THREAD

**Issue by luuhq** [turn-project/turn#68]
Can there be an option that the output only display failed tests?

Each of my test class has a butt load of tests and that'll be really handy!

**Comment by trans** [comment]
Hmm... a new report format might be the best choice for this. In fact, you should try the dotted reporter. In you helper,

```
Turn.config.format = :dotted
```

Or on the command line

```
$ turn -D ...
```

I think that does what you want.

**Comment by luuhq** [comment]
That does it. Thanks!
