### ISSUE TITLE
Turn with Spork and Test::Unit - Test Either not running

### ISSUE THREAD

**Issue by taelor** [turn-project/turn#70]
I've been working getting our integration tests to run using Test::Unit, Capybara, Spork, and Guard. We've been using Turn and love the output when running tests. 

But it takes us 15 seconds (on a patched ruby 1.9.3) just to boot Rails, so Spork really helps cut down on that testing time.

Below you can see the three cases. We know that each of Spork and turn are working when run without the other being turned on, but when you enable both of them, the tests don't actually run. I have even made test that purposely fails, but it still shows "pass: 0,  fail: 0,  error: 0 total: 0 tests with 0 assertions in 0.004036 seconds" on one that should most definitely fail. Even tests that should be throwing exceptions are not.

If you could point me in the right direction on what I would need to do to get the two tool to work together, I would love to work on this for you.

```
###############################################################
# Turn : false
# Spork : true
###############################################################
bash$ testdrb -Itest test/integration/nurse_notes_test.rb 
Loaded suite NurseNotesTest
Started


Finished in 4.351769 seconds.

2 tests, 3 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
0% passed

0.46 tests/s, 0.69 assertions/s



###############################################################
# Turn : true
# Spork : false
###############################################################
bash$ ruby -Itest test/integration/nurse_notes_test.rb 

LOADED SUITE test,test/integration,test/support,test/unit

ActionController::TestCase
ActionDispatch::IntegrationTest
ActiveRecord::TestCase
ActiveSupport::TestCase
NurseNotesTest
     test_nurse_note_has_show                                             PASS
     test_nurse_note_has_summary                                          PASS
Test::Unit::TestCase
==============================================================================
  pass: 2,  fail: 0,  error: 0
  total: 2 tests with 3 assertions in 2.797512 seconds
==============================================================================



###############################################################
# Turn : true
# Spork : true
###############################################################
bash$ testdrb -Itest test/integration/nurse_notes_test.rb 
LOADED SUITE test/integration

==============================================================================
  pass: 0,  fail: 0,  error: 0
  total: 0 tests with 0 assertions in 0.004036 seconds
==============================================================================
```

**Comment by trans** [comment]
I haven't ever used Spork so bare with me here.

First the website mentions support for RSpec and Cucumber, and says `spork-testunit` gem is needed for TestUnit. Have you tried that? Technically, Turn has moved on to MiniTest, so I'm not sure if by TestUnit they mean something that will work with both TestUnit and MiniTest (since MiniTest has a TestUnit compatability layer), or not. 

Also, I assume you are using `spork-rails`, but just to be sure, read https://github.com/sporkrb/spork/wiki/Supported-Application-Frameworks

**Comment by aspiers** [comment]
+1 - my app startup is way too long to be able to efficiently test without Spork.  I'd love to have turn-formatted output too.  @taelor what steps are you taking to simultaneously enable Spork and turn?  It's not at all clear to me how this should be done, due to issue #67.

**Comment by taelor** [comment]
trans,

Yes, we do have spork-testunit in our gemfile.

I think the spork-rails is for Rails 2.3 apps. You don't need it in Rails 3.

aspiers,
first off, i can't believe I didnt see your issue. had I seen it, I would have just added my thoughts to that thread.

I haven't found a way to enable both yet.

**Comment by aspiers** [comment]
taelor wrote:

> I haven't found a way to enable both yet.

Err, but just a few comments up from this one, you said you did.  You wrote:

```
###############################################################
# Turn : true
# Spork : true
###############################################################
bash$ testdrb -Itest test/integration/nurse_notes_test.rb 
LOADED SUITE test/integration

==============================================================================
  pass: 0,  fail: 0,  error: 0
  total: 0 tests with 0 assertions in 0.004036 seconds
==============================================================================
```

What I want to know is what configuration you were trying when you did that.

**Comment by taelor** [comment]
this is what would be in my gemfile for that situation.

``` ruby
group :test do
  gem 'turn'
  gem 'capybara'
  gem 'launchy'
  gem 'spork', '~> 0.9.0.rc9'
  gem 'spork-testunit', :git => 'git://github.com/sporkrb/spork-testunit'
  gem 'guard-spork'
  gem 'guard-test'
end
```

**Comment by aspiers** [comment]
@taelor Thanks - and where / how do you require `turn`?

**Comment by trans** [comment]
This issue is fixed with latest release. But it does require a major change to usage. From now on use

```
require 'turn/autorun'
```

in `test_helper.rb`, instead of just `require 'turn'`.
