### ISSUE TITLE
Pretty reporter issue

### ISSUE THREAD

**Issue by berk** [turn-project/turn#84]
Please take a look at the following line:

https://github.com/TwP/turn/blob/master/lib/turn/reporters/pretty_reporter.rb#L134

The first parameter assigns a default value, while the second doesn't. This raises an exception in the last couple of versions of the gem.

We are using Ruby 1.8.7 with Rails 2.3.11

Thank you.

**Comment by lcowell** [comment]
I was just looking at the same issue, so I removed the default assignment locally and the test suite still passed. 

I'm probably missing something, but I'm not sure what the purpose of message=nil is as the only value that will trigger the default assignment would be nil and it's being assigned that very same value.

**Comment by trans** [comment]
Thanks. I'll fix. It was part of recent patch and I didn't catch it. I think somehow the arguments were supposed to be reverse.

**Comment by y8** [comment]
Yup, my fault. I've thought that turn not supposed to work with 1.8.x :)

**Comment by trans** [comment]
Ok. Will be out in next release.
