### ISSUE TITLE
Bug or 1.9 in pretty_reporter.rb?

### ISSUE THREAD

**Issue by djberg96** [turn-project/turn#89]
On line 134 of pretty_reporter.rb (version 0.9.4) you have this:

<pre>
def prettify(message=nil, raised)
</pre>

This is illegal in 1.8. Was that intentional? It seems the args were flipped (and thus legal for 1.8) in the previous release.

If Turn is going to be 1.9 only, may I suggest updating the gemspec and setting required_ruby_version?

Regards,

Dan

**Comment by trans** [comment]
Nope. And it's been fixed. I'll release soon.
