### ISSUE TITLE
Command line runner does not return proper exit code

### ISSUE THREAD

**Issue by defunkt** [turn-project/turn#9]
Patch: http://github.com/defunkt/turn/commit/proper_exit_code

Before and after: https://gist.github.com/18604d36fa844b8b835d

**Comment by rtomayko** [comment]
You do know you have commit rights on this project, yes?

I've noticed the exit status before too. Usually when I try to use turn from rake and want rake to fail if turn fails.

**Comment by defunkt** [comment]
What?

**Comment by defunkt** [comment]
Closed in 050751c6529acf21c64f565fb8b6fa68b896d063
