### ISSUE TITLE
Misleading error

### ISSUE THREAD

**Issue by paneq** [turn-project/turn#98]
```
/home/rupert/develop/Yoke-bot/.bundle/ruby/1.9.1/gems/turn-0.9.6/lib/turn/minitest.rb:23:in `<top (required)>': MiniTest v1.6.0 is out of date. (RuntimeError)
`gem install minitest` and add `gem 'minitest' to you test helper.
```

This of course might be helpful in some cases however I found out that adding `gem "minitest"` to `Gemfile` works way better for me in many cases. I suggest changing the message to:

```
add `gem 'minitest' to you test helper and/or Gemfile
```

What do you think ?

**Comment by trans** [comment]
Agreed.

**Comment by trans** [comment]
Feel free to submit a patch. Otherwise I will get to it eventually --not at the top of the priority list at the moment though.

**Comment by trans** [comment]
I just changed it to "Please update to a later version."
